#!/usr/bin/env bash
# Start the Irie Fishmongers demo stack (backend :3001, storefront :3000,
# admin :3002) with environment derived from where it is running.
#
# - In GitHub Codespaces, public URLs are derived from CODESPACE_NAME +
#   GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN (never hard-coded).
# - Outside Codespaces (VS Code Desktop devcontainer), localhost is used.
# - Frontend URLs are written to apps/*/.env.local (git-ignored). Next.js
#   loads and watches these natively, so they survive restarts, reach
#   next.config.js (the admin CSP derives connect-src from the API URL),
#   and are not subject to Turbo's strict-env filtering. When the API URL
#   OR an app's source changes, stale .next build caches are cleared -
#   NEXT_PUBLIC_* values are inlined at compile time and cached, so a
#   restart alone is not enough to pick up a new value.
# - Startup is verified by polling real HTTP endpoints, not log text.
#
# This is a DEMO/smoke-test environment, not formal UAT (that is Azure,
# Phase 17). Stop with scripts/stop-codespaces-demo.sh.
set -euo pipefail

cd "$(dirname "$0")/.."

PID_FILE=/tmp/irie-dev.pid
LOG_FILE=/tmp/irie-dev.log

# --- 1. Derive public URLs from the environment (no hard-coded hostnames) ---
# FRONTEND_API_URL is what the BROWSER calls; PROXY_TARGET is where Next
# forwards it server-side. In Codespaces each forwarded *.app.github.dev port
# is its own site (Public Suffix List) - a cross-port browser fetch hits
# GitHub's per-port interstitial and a cross-site cookie. So there the browser
# calls the app's OWN origin ("/api/v1") and Next proxies to localhost:3001
# inside the container: same-origin, no interstitial, no CORS, SameSite=strict
# works. Locally, localhost ports share a site, so a direct URL is simplest.
if [[ -n "${CODESPACE_NAME:-}" ]]; then
  DOMAIN="${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-app.github.dev}"
  WEB_URL="https://${CODESPACE_NAME}-3000.${DOMAIN}"
  API_ROOT="https://${CODESPACE_NAME}-3001.${DOMAIN}"
  ADMIN_URL="https://${CODESPACE_NAME}-3002.${DOMAIN}"
  FRONTEND_API_URL="/api/v1"
  PROXY_TARGET="http://localhost:3001"
else
  WEB_URL="http://localhost:3000"
  API_ROOT="http://localhost:3001"
  ADMIN_URL="http://localhost:3002"
  FRONTEND_API_URL="${API_ROOT}/api/v1"
  PROXY_TARGET=""
fi

# --- 2. Backend runtime env (verified contract, see backend/src/config) ---
# APP_BASE_URL is the backend's OWN base URL (WiPay webhook response_url).
export APP_BASE_URL="${API_ROOT}"
export CORS_ORIGIN="${WEB_URL},${ADMIN_URL}"
# Safe demo fallbacks so live email/push/payments can never be contacted if
# the container env did not already provide (invalid) demo values.
export SENDGRID_API_KEY="${SENDGRID_API_KEY:-demo-disabled}"
export SENDGRID_FROM_EMAIL="${SENDGRID_FROM_EMAIL:-demo@demo.iriefishmongers.test}"
export FCM_SERVER_KEY="${FCM_SERVER_KEY:-demo-disabled}"
export WIPAY_ACCOUNT_NUMBER="${WIPAY_ACCOUNT_NUMBER:-demo-disabled}"
export WIPAY_API_KEY="${WIPAY_API_KEY:-demo-disabled}"
export ENABLE_SCHEDULER="${ENABLE_SCHEDULER:-true}"

# --- 3. Frontend env via .env.local (git-ignored; Next loads these itself) ---
# Verified contract: apps/web reads only NEXT_PUBLIC_API_URL;
# apps/admin-dashboard reads NEXT_PUBLIC_API_URL, NEXT_PUBLIC_ENVIRONMENT,
# and NEXT_PUBLIC_APP_URL = the ADMIN app's own URL (lib/env.ts).
NEW_API_URL="${FRONTEND_API_URL}"
# The optional proxy line - Next reads API_PROXY_TARGET from .env.local to set
# up the server-side rewrite (see apps/*/next.config.js).
PROXY_LINE=""
[[ -n "$PROXY_TARGET" ]] && PROXY_LINE="API_PROXY_TARGET=${PROXY_TARGET}"
# Capture the previously-compiled URL BEFORE overwriting, to decide whether
# the .next cache is stale. .env.local lives on the same persistent volume as
# .next (unlike a /tmp stamp, which is wiped on Codespace restart while .next
# survives - the exact cause of a rebuilt server still serving localhost).
OLD_API_URL="$(grep -h '^NEXT_PUBLIC_API_URL=' apps/admin-dashboard/.env.local 2>/dev/null | cut -d= -f2- || true)"
cat >apps/web/.env.local <<ENV
# Generated by scripts/start-codespaces-demo.sh - do not edit or commit.
NEXT_PUBLIC_API_URL=${NEW_API_URL}
${PROXY_LINE}
ENV
cat >apps/admin-dashboard/.env.local <<ENV
# Generated by scripts/start-codespaces-demo.sh - do not edit or commit.
NEXT_PUBLIC_API_URL=${NEW_API_URL}
NEXT_PUBLIC_ENVIRONMENT=development
NEXT_PUBLIC_APP_URL=${ADMIN_URL}
${PROXY_LINE}
ENV

# --- 3b. Neutralize any shell-level NEXT_PUBLIC_* override (managed demo only) ---
# Next.js gives process.env PRECEDENCE over .env.local, so a NEXT_PUBLIC_*
# exported into this shell (e.g. still declared in .devcontainer/docker-compose.yml,
# or a shell profile / Codespaces secret) would silently override the per-app
# .env.local we just wrote and re-inject a wrong API URL into the compiled bundle
# - the failure mode that looks like a "stale cache" but survives every rebuild.
#
# Scope matters: we only UNSET inside the managed demo container (Codespaces or a
# devcontainer), where .env.local is unambiguously owned by this script. Anywhere
# else (e.g. run on a bare host) a NEXT_PUBLIC_* may be deliberate developer
# config, so we WARN but never silently erase it. The durable fix in-container is
# to remove the source and REBUILD (a running container keeps exporting it).
if [[ "${CODESPACES:-}" == "true" || -n "${CODESPACE_NAME:-}" || -f /.dockerenv ]]; then
  for _pub in NEXT_PUBLIC_API_URL NEXT_PUBLIC_ENVIRONMENT NEXT_PUBLIC_APP_URL; do
    if [[ -n "${!_pub:-}" ]]; then
      echo "==> WARNING: ${_pub}=${!_pub} is set in the container environment - unsetting" >&2
      echo "    it so the generated apps/*/.env.local takes effect. Remove it from" >&2
      echo "    .devcontainer/docker-compose.yml and REBUILD the container to fix permanently." >&2
      unset "$_pub"
    fi
  done
else
  for _pub in NEXT_PUBLIC_API_URL NEXT_PUBLIC_ENVIRONMENT NEXT_PUBLIC_APP_URL; do
    if [[ -n "${!_pub:-}" ]]; then
      echo "==> WARNING: ${_pub}=${!_pub} is set in your shell and will OVERRIDE the generated" >&2
      echo "    apps/*/.env.local (Next gives process.env precedence). Left untouched because" >&2
      echo "    this is not a managed demo container; unset it yourself to use the demo value." >&2
    fi
  done
fi
unset _pub

# --- 4. Clear stale Next build caches (compiled API URL OR source changed) ---
# NEXT_PUBLIC_* is inlined at compile time and cached, so a restart alone does
# not pick up a new value. Two independent things can make a cached .next stale:
#   (a) the compiled API URL changed - a .env.local value, tracked in step 3; or
#   (b) the app's own SOURCE changed - e.g. a `git pull` that edits lib/env.ts
#       or next.config.js - while the URL stayed the same. The URL heuristic
#       alone misses (b), so a rebuilt bundle keeps serving old inlined values
#       (exactly how the env.ts inlining fix could go unnoticed after a pull).
# Guard both, per app. The source fingerprint is the git tree hash of the app's
# committed files plus a hash of any uncommitted tracked changes, so ANY source
# edit - a pulled commit or a local diff - invalidates the cache. It is stamped
# inside .next itself: .next lives on the same persistent volume and is wiped
# exactly when we clear, so a missing stamp always forces a safe rebuild.
STAMP=".next/.build-source"
# Stable fingerprint of an app's tracked source ("" segments if git is absent).
source_fingerprint() {
  local app="$1" tree diff
  tree="$(git rev-parse "HEAD:$app" 2>/dev/null || true)"
  diff="$(git diff -- "$app" 2>/dev/null | git hash-object --stdin 2>/dev/null || true)"
  printf '%s:%s' "$tree" "$diff"
}
clear_next_if_stale() {
  local app="$1" fp prev reason=''
  fp="$(source_fingerprint "$app")"
  prev="$([[ -f "$app/$STAMP" ]] && cat "$app/$STAMP" 2>/dev/null || true)"
  if [[ "$OLD_API_URL" != "$NEW_API_URL" ]]; then
    reason="API URL changed (was: ${OLD_API_URL:-none})"
  elif [[ -z "$prev" ]]; then
    reason='no prior build record'
  elif [[ "$fp" != "$prev" ]]; then
    reason='source changed since last build'
  fi
  if [[ -n "$reason" ]]; then
    echo "==> ${app}: ${reason} - clearing Next.js build cache"
    rm -rf "$app/.next"
  fi
  mkdir -p "$app/.next"
  printf '%s' "$fp" >"$app/$STAMP"
}
clear_next_if_stale apps/web
clear_next_if_stale apps/admin-dashboard

# --- 5. Preconditions: deps installed, database and redis reachable ---
if [[ ! -d node_modules ]]; then
  echo "ERROR: node_modules missing - run 'bash .devcontainer/setup.sh' first." >&2
  exit 1
fi
check_tcp() {
  node -e "
const s=require('net').connect($2,'$1');
s.on('connect',()=>{s.end();process.exit(0)});
s.on('error',()=>process.exit(1));
setTimeout(()=>process.exit(1),3000);" 2>/dev/null
}
DB_HOST=db; REDIS_HOST=redis
check_tcp "$DB_HOST" 5432 || { DB_HOST=localhost; check_tcp "$DB_HOST" 5432; } \
  || { echo "ERROR: PostgreSQL is not reachable (db/localhost:5432)." >&2; exit 1; }
check_tcp "$REDIS_HOST" 6379 || { REDIS_HOST=localhost; check_tcp "$REDIS_HOST" 6379; } \
  || { echo "ERROR: Redis is not reachable (redis/localhost:6379)." >&2; exit 1; }
echo "==> PostgreSQL and Redis reachable"

# --- 6. Stop any previous run (whole process tree), then start ONCE ---
bash "$(dirname "$0")/stop-codespaces-demo.sh" quiet || true
echo "==> Starting dev servers (logs: ${LOG_FILE})"
setsid nohup npm run dev >"$LOG_FILE" 2>&1 &
DEV_PID=$!
echo "$DEV_PID" >"$PID_FILE"

# --- 7. Poll real HTTP endpoints (via localhost - immune to the Codespaces
#        port-visibility interstitial). Any HTTP status proves the server is
#        up; the API must additionally return a healthy /health. ---
http_code() { curl -s -o /dev/null -w '%{http_code}' --max-time 4 "$1" 2>/dev/null || echo 000; }
for attempt in $(seq 1 36); do
  api_ok=false; web_ok=false; admin_ok=false
  curl -fsS --max-time 4 "http://localhost:3001/api/v1/health" >/dev/null 2>&1 && api_ok=true
  [[ "$(http_code http://localhost:3000)" != "000" ]] && web_ok=true
  [[ "$(http_code http://localhost:3002)" != "000" ]] && admin_ok=true
  if $api_ok && $web_ok && $admin_ok; then
    cat <<DONE

============================================================
 All services are ready.
   Customer Storefront : ${WEB_URL}
   Admin Dashboard     : ${ADMIN_URL}
   (both call the API on their OWN origin via /api/v1 - Next proxies it to
    the backend inside the container, so the browser never touches port 3001)

 Demo logins (password: DemoPass!23):
   admin@demo.iriefishmongers.test      (admin dashboard)
   vendor@demo.iriefishmongers.test
   customer@demo.iriefishmongers.test
   driver@demo.iriefishmongers.test

 Codespaces: set ONLY ports 3000 and 3002 visibility (Ports tab) to Public
 (open demo) or Organization (confidential). Port 3001 stays internal - the
 same-origin proxy means no cross-port GitHub interstitial and no CORS.
 Stop with: bash scripts/stop-codespaces-demo.sh
============================================================
DONE
    exit 0
  fi
  if ! kill -0 "$DEV_PID" 2>/dev/null; then
    echo "ERROR: dev process exited unexpectedly - last 60 log lines:" >&2
    tail -60 "$LOG_FILE" >&2
    exit 1
  fi
  sleep 5
done
echo "ERROR: timed out waiting for services - last 60 log lines:" >&2
tail -60 "$LOG_FILE" >&2
exit 1
