#!/usr/bin/env bash
# Start the Irie Fishmongers demo stack (backend :3001, storefront :3000,
# admin :3002) with environment derived from where it is running.
#
# - In GitHub Codespaces, public URLs are derived from CODESPACE_NAME +
#   GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN (never hard-coded).
# - Outside Codespaces (VS Code Desktop devcontainer), localhost is used.
# - Frontend URLs are written to apps/*/.env.local (git-ignored). Next.js
#   loads and watches these natively, so they survive restarts, reach
#   next.config.js (the admin CSP derives connect-src from the API URL),
#   and are not subject to Turbo's strict-env filtering. When the API URL
#   changes, stale .next build caches are cleared - NEXT_PUBLIC_* values
#   are inlined at compile time and cached, so a restart alone is not
#   enough to pick up a new value.
# - Startup is verified by polling real HTTP endpoints, not log text.
#
# This is a DEMO/smoke-test environment, not formal UAT (that is Azure,
# Phase 17). Stop with scripts/stop-codespaces-demo.sh.
set -euo pipefail

cd "$(dirname "$0")/.."

PID_FILE=/tmp/irie-dev.pid
LOG_FILE=/tmp/irie-dev.log
URL_STAMP=/tmp/irie-demo-api-url

# --- 1. Derive public URLs from the environment (no hard-coded hostnames) ---
if [[ -n "${CODESPACE_NAME:-}" ]]; then
  DOMAIN="${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-app.github.dev}"
  WEB_URL="https://${CODESPACE_NAME}-3000.${DOMAIN}"
  API_ROOT="https://${CODESPACE_NAME}-3001.${DOMAIN}"
  ADMIN_URL="https://${CODESPACE_NAME}-3002.${DOMAIN}"
  # Each forwarded *.app.github.dev port is its own SITE (Public Suffix
  # List), so the refresh cookie is cross-site here and needs SameSite=None
  # (which forces Secure - fine, Codespaces forwarding is HTTPS). Local
  # devcontainers keep the strict default: localhost ports share a site.
  export REFRESH_COOKIE_SAMESITE="${REFRESH_COOKIE_SAMESITE:-none}"
else
  WEB_URL="http://localhost:3000"
  API_ROOT="http://localhost:3001"
  ADMIN_URL="http://localhost:3002"
fi

# --- 2. Backend runtime env (verified contract, see backend/src/config) ---
# APP_BASE_URL is the backend's OWN base URL (WiPay webhook response_url).
export APP_BASE_URL="${API_ROOT}"
export CORS_ORIGIN="${WEB_URL},${ADMIN_URL}"
# Safe demo fallbacks so live email/push/payments can never be contacted if
# the container env did not already provide (invalid) demo values.
export SENDGRID_API_KEY="${SENDGRID_API_KEY:-demo-disabled}"
export SENDGRID_FROM_EMAIL="${SENDGRID_FROM_EMAIL:-demo@demo.iriefishmongers.test}"
export FCM_SERVER_KEY="${FCM_SERVER_KEY:-demo-disabled}"
export WIPAY_ACCOUNT_NUMBER="${WIPAY_ACCOUNT_NUMBER:-demo-disabled}"
export WIPAY_API_KEY="${WIPAY_API_KEY:-demo-disabled}"
export ENABLE_SCHEDULER="${ENABLE_SCHEDULER:-true}"

# --- 3. Frontend env via .env.local (git-ignored; Next loads these itself) ---
# Verified contract: apps/web reads only NEXT_PUBLIC_API_URL;
# apps/admin-dashboard reads NEXT_PUBLIC_API_URL, NEXT_PUBLIC_ENVIRONMENT,
# and NEXT_PUBLIC_APP_URL = the ADMIN app's own URL (lib/env.ts).
cat >apps/web/.env.local <<ENV
# Generated by scripts/start-codespaces-demo.sh - do not edit or commit.
NEXT_PUBLIC_API_URL=${API_ROOT}/api/v1
ENV
cat >apps/admin-dashboard/.env.local <<ENV
# Generated by scripts/start-codespaces-demo.sh - do not edit or commit.
NEXT_PUBLIC_API_URL=${API_ROOT}/api/v1
NEXT_PUBLIC_ENVIRONMENT=development
NEXT_PUBLIC_APP_URL=${ADMIN_URL}
ENV

# --- 4. Clear stale Next build caches if the API URL changed ---
if [[ ! -f "$URL_STAMP" || "$(cat "$URL_STAMP")" != "$API_ROOT" ]]; then
  echo "==> API URL changed - clearing Next.js build caches"
  rm -rf apps/web/.next apps/admin-dashboard/.next
  echo "$API_ROOT" >"$URL_STAMP"
fi

# --- 5. Preconditions: deps installed, database and redis reachable ---
if [[ ! -d node_modules ]]; then
  echo "ERROR: node_modules missing - run 'bash .devcontainer/setup.sh' first." >&2
  exit 1
fi
check_tcp() {
  node -e "
const s=require('net').connect($2,'$1');
s.on('connect',()=>{s.end();process.exit(0)});
s.on('error',()=>process.exit(1));
setTimeout(()=>process.exit(1),3000);" 2>/dev/null
}
DB_HOST=db; REDIS_HOST=redis
check_tcp "$DB_HOST" 5432 || { DB_HOST=localhost; check_tcp "$DB_HOST" 5432; } \
  || { echo "ERROR: PostgreSQL is not reachable (db/localhost:5432)." >&2; exit 1; }
check_tcp "$REDIS_HOST" 6379 || { REDIS_HOST=localhost; check_tcp "$REDIS_HOST" 6379; } \
  || { echo "ERROR: Redis is not reachable (redis/localhost:6379)." >&2; exit 1; }
echo "==> PostgreSQL and Redis reachable"

# --- 6. Stop any previous run (whole process tree), then start ONCE ---
bash "$(dirname "$0")/stop-codespaces-demo.sh" quiet || true
echo "==> Starting dev servers (logs: ${LOG_FILE})"
setsid nohup npm run dev >"$LOG_FILE" 2>&1 &
DEV_PID=$!
echo "$DEV_PID" >"$PID_FILE"

# --- 7. Poll real HTTP endpoints (via localhost - immune to the Codespaces
#        port-visibility interstitial). Any HTTP status proves the server is
#        up; the API must additionally return a healthy /health. ---
http_code() { curl -s -o /dev/null -w '%{http_code}' --max-time 4 "$1" 2>/dev/null || echo 000; }
for attempt in $(seq 1 36); do
  api_ok=false; web_ok=false; admin_ok=false
  curl -fsS --max-time 4 "http://localhost:3001/api/v1/health" >/dev/null 2>&1 && api_ok=true
  [[ "$(http_code http://localhost:3000)" != "000" ]] && web_ok=true
  [[ "$(http_code http://localhost:3002)" != "000" ]] && admin_ok=true
  if $api_ok && $web_ok && $admin_ok; then
    cat <<DONE

============================================================
 All services are ready.
   Customer Storefront : ${WEB_URL}   (deep-link only - see README)
   Backend API         : ${API_ROOT}/api/v1   (Swagger: /api/v1/docs)
   Admin Dashboard     : ${ADMIN_URL}

 Demo logins (password: DemoPass!23):
   admin@demo.iriefishmongers.test      (admin dashboard)
   vendor@demo.iriefishmongers.test
   customer@demo.iriefishmongers.test
   driver@demo.iriefishmongers.test

 Codespaces: set ports 3000/3001/3002 visibility (Ports tab) to
 Public (open demo) or Organization (confidential) before sharing.
 Stop with: bash scripts/stop-codespaces-demo.sh
============================================================
DONE
    exit 0
  fi
  if ! kill -0 "$DEV_PID" 2>/dev/null; then
    echo "ERROR: dev process exited unexpectedly - last 60 log lines:" >&2
    tail -60 "$LOG_FILE" >&2
    exit 1
  fi
  sleep 5
done
echo "ERROR: timed out waiting for services - last 60 log lines:" >&2
tail -60 "$LOG_FILE" >&2
exit 1
