import { Injectable, Logger } from '@nestjs/common';
import { CheckoutAttempt, Prisma } from '@prisma/client';

import { CheckoutAttemptRepository } from '../repositories/checkout-attempt.repository';
import {
  CheckoutAttemptInputValidationFailure,
  CheckoutAttemptSummary,
  CreateOrResumeCheckoutAttemptInput,
  CreateOrResumeCheckoutAttemptResult,
  FindStaleCheckoutAttemptsInput,
  FindStaleCheckoutAttemptsResult,
  MarkCheckoutAttemptCommittedResult,
  MarkCheckoutAttemptFailedResult,
  UpdateCheckoutHeartbeatResult,
} from '../types/checkout-attempt.types';

const DEFAULT_STALE_PAGE_SIZE = 100;
const MAX_STALE_PAGE_SIZE = 200;
const MAX_FAILURE_CODE_LENGTH = 64;
const MAX_FAILURE_MESSAGE_LENGTH = 500;
const HEARTBEAT_FUTURE_SKEW_TOLERANCE_MS = 30_000;

// Owns every business rule for CheckoutAttempt lifecycle transitions (see
// docs/integrations/ADR-007-checkout-cutover-and-operational-integration.md).
// CheckoutAttemptRepository is the only class that queries
// prisma.checkoutAttempt; this service never does so directly. Additive
// and unwired - CheckoutAttemptModule is not imported by any production
// module yet.
@Injectable()
export class CheckoutAttemptService {
  private readonly logger = new Logger(CheckoutAttemptService.name);

  constructor(private readonly repository: CheckoutAttemptRepository) {}

  async createOrResume(
    input: CreateOrResumeCheckoutAttemptInput,
  ): Promise<CreateOrResumeCheckoutAttemptResult> {
    const { attempt, created } = await this.repository.createOrGetByIdempotencyKey({
      idempotencyKey: input.idempotencyKey,
      cartId: input.cartId,
      customerId: input.customerId,
      now: input.now,
    });

    if (attempt.customerId !== input.customerId || attempt.cartId !== input.cartId) {
      // Never exposed publicly (Decision 1) - internal structured log only.
      this.logger.warn('checkout attempt idempotency key reused with mismatched ownership', {
        idempotencyKey: input.idempotencyKey,
        mismatchType: attempt.customerId !== input.customerId ? 'customerId' : 'cartId',
      });
      return { ok: false, code: 'IDEMPOTENCY_KEY_CONFLICT' };
    }

    const summary = CheckoutAttemptService.toSummary(attempt);

    if (created) {
      return { ok: true, action: 'CREATED', attempt: summary };
    }

    // Existing row, ownership confirmed - classify by status.
    // createOrResume never mutates lastHeartbeatAt for a resumed row.
    switch (attempt.status) {
      case 'PROCESSING':
        return { ok: true, action: 'RESUMED_PROCESSING', attempt: summary };
      case 'COMMITTED':
        return { ok: true, action: 'ALREADY_COMMITTED', attempt: summary };
      case 'FAILED':
        return { ok: true, action: 'ALREADY_FAILED', attempt: summary };
    }
  }

  // Narrows the raw Prisma row to the public-facing shape - deliberately
  // never includes failureMessage (see CheckoutAttemptSummary).
  private static toSummary(attempt: CheckoutAttempt): CheckoutAttemptSummary {
    return {
      id: attempt.id,
      idempotencyKey: attempt.idempotencyKey,
      cartId: attempt.cartId,
      customerId: attempt.customerId,
      status: attempt.status,
      orderId: attempt.orderId,
      failureCode: attempt.failureCode,
      createdAt: attempt.createdAt,
      updatedAt: attempt.updatedAt,
      lastHeartbeatAt: attempt.lastHeartbeatAt,
    };
  }

  async updateHeartbeat(
    attemptId: string,
    customerId: string,
    now: Date,
  ): Promise<UpdateCheckoutHeartbeatResult> {
    // now is server-generated by the future coordinator, never trusted
    // from a public client - this check guards against clock skew across
    // services/processes, not against an untrusted caller.
    if (now.getTime() - Date.now() > HEARTBEAT_FUTURE_SKEW_TOLERANCE_MS) {
      return {
        ok: false,
        code: 'INVALID_INPUT',
        field: 'now',
        reason: 'now cannot be more than 30 seconds ahead of the server clock',
      };
    }

    const { count } = await this.repository.updateHeartbeatIfProcessing(attemptId, customerId, now);
    if (count === 1) {
      return { ok: true };
    }

    // The conditional write matched zero rows - re-read only to classify
    // why (Decision 5). The database transition itself was already
    // atomic; this is an observation after the fact, not a second attempt.
    const existing = await this.repository.findById(attemptId);
    if (!existing) {
      return { ok: false, code: 'NOT_FOUND' };
    }
    if (existing.customerId !== customerId) {
      return { ok: false, code: 'OWNERSHIP_MISMATCH' };
    }
    if (existing.status !== 'PROCESSING') {
      return { ok: false, code: 'NOT_PROCESSING' };
    }
    // Status is PROCESSING and ownership matches, so the only remaining
    // reason the conditional update missed is the lastHeartbeatAt <= now
    // monotonicity guard.
    return { ok: false, code: 'HEARTBEAT_NOT_MONOTONIC' };
  }

  async markCommittedInTransaction(
    tx: Prisma.TransactionClient,
    attemptId: string,
    customerId: string,
    orderId: string,
    now: Date,
  ): Promise<MarkCheckoutAttemptCommittedResult> {
    const { count } = await this.repository.markCommitted(tx, attemptId, customerId, orderId, now);
    if (count === 1) {
      return { ok: true, alreadyCommitted: false };
    }

    const existing = await this.repository.findById(attemptId, tx);
    if (!existing) {
      return { ok: false, code: 'NOT_FOUND' };
    }
    if (existing.customerId !== customerId) {
      return { ok: false, code: 'OWNERSHIP_MISMATCH' };
    }
    if (existing.status === 'FAILED') {
      return { ok: false, code: 'INVALID_TRANSITION' };
    }
    if (existing.status === 'COMMITTED') {
      if (existing.orderId === orderId) {
        return { ok: true, alreadyCommitted: true };
      }
      if (existing.orderId === null) {
        throw new Error(
          `Internal consistency error: checkout attempt ${attemptId} is COMMITTED with no orderId`,
        );
      }
      return { ok: false, code: 'ORDER_CONFLICT', existingOrderId: existing.orderId };
    }
    // existing.status === 'PROCESSING' with matching ownership should have
    // been matched by the conditional update above - structurally
    // impossible under this method's own transaction snapshot.
    throw new Error(
      `Internal consistency error: checkout attempt ${attemptId} is PROCESSING with matching ` +
        'ownership but the conditional commit update matched zero rows',
    );
  }

  async markFailed(
    attemptId: string,
    customerId: string,
    failureCode: string,
    failureMessage: string | null,
    now: Date,
  ): Promise<MarkCheckoutAttemptFailedResult> {
    const codeError = CheckoutAttemptService.validateFailureCode(failureCode);
    if (codeError) {
      return { ok: false, code: 'INVALID_INPUT', field: 'failureCode', reason: codeError };
    }

    // failureMessage is sanitized, never rejected - unsafe message content
    // must never prevent the PROCESSING -> FAILED transition itself.
    const trimmedCode = failureCode.trim();
    const sanitizedMessage = CheckoutAttemptService.sanitizeFailureMessage(failureMessage);
    const { count } = await this.repository.markFailed(
      attemptId,
      customerId,
      trimmedCode,
      sanitizedMessage,
      now,
    );
    if (count === 1) {
      return { ok: true, alreadyFailed: false, detailsMatched: true };
    }

    const existing = await this.repository.findById(attemptId);
    if (!existing) {
      return { ok: false, code: 'NOT_FOUND' };
    }
    if (existing.customerId !== customerId) {
      return { ok: false, code: 'OWNERSHIP_MISMATCH' };
    }
    if (existing.status === 'COMMITTED') {
      return { ok: false, code: 'INVALID_TRANSITION' };
    }
    if (existing.status === 'PROCESSING') {
      throw new Error(
        `Internal consistency error: checkout attempt ${attemptId} is PROCESSING with matching ` +
          'ownership but the conditional fail update matched zero rows',
      );
    }

    // existing.status === 'FAILED' - first PROCESSING -> FAILED write
    // wins (Decision 6): preserve it, never overwrite with a later,
    // possibly-different failure. Compared against the sanitized
    // representation on both sides - the stored value was itself
    // sanitized on write, so this is never a raw-vs-sanitized mismatch.
    const detailsMatched =
      existing.failureCode === trimmedCode && existing.failureMessage === sanitizedMessage;
    if (!detailsMatched) {
      this.logger.warn(
        'checkout attempt duplicate failure with different details - preserving first recorded failure',
        { attemptId, storedFailureCode: existing.failureCode, newFailureCode: trimmedCode },
      );
    }
    return { ok: true, alreadyFailed: true, detailsMatched };
  }

  async findStalePage(input: FindStaleCheckoutAttemptsInput): Promise<FindStaleCheckoutAttemptsResult> {
    const limit = input.limit ?? DEFAULT_STALE_PAGE_SIZE;
    const validationFailure = CheckoutAttemptService.validateStalePageInput(input, limit);
    if (validationFailure) {
      return validationFailure;
    }

    const rows = await this.repository.findStaleProcessing({
      heartbeatBefore: input.heartbeatBefore,
      cursor: input.cursor,
      limit: limit + 1,
    });

    const hasMore = rows.length > limit;
    const pageRows = hasMore ? rows.slice(0, limit) : rows;
    const items = pageRows.map((row) => ({
      id: row.id,
      idempotencyKey: row.idempotencyKey,
      cartId: row.cartId,
      customerId: row.customerId,
      lastHeartbeatAt: row.lastHeartbeatAt,
    }));
    const last = items[items.length - 1];
    const nextCursor = hasMore && last ? { lastHeartbeatAt: last.lastHeartbeatAt, id: last.id } : null;

    return { ok: true, page: { items, nextCursor } };
  }

  private static validateFailureCode(failureCode: string): string | null {
    const trimmed = failureCode.trim();
    if (trimmed.length === 0) {
      return 'failureCode cannot be empty';
    }
    if (trimmed.length > MAX_FAILURE_CODE_LENGTH) {
      return `failureCode must be ${MAX_FAILURE_CODE_LENGTH} characters or fewer`;
    }
    return null;
  }

  // Sanitizes rather than rejects - unsafe message content must never
  // block the PROCESSING -> FAILED transition itself. Strips Node/V8
  // stack-trace frame lines, redacts the most common credential/token
  // shapes (no prior sanitization convention exists elsewhere in this
  // codebase to reuse - this is a self-contained, conservative
  // implementation), trims, and caps the final result to
  // MAX_FAILURE_MESSAGE_LENGTH. A message that sanitizes down to nothing
  // is stored as null rather than an empty string.
  private static sanitizeFailureMessage(failureMessage: string | null): string | null {
    if (failureMessage === null) {
      return null;
    }

    const withoutStackLines = failureMessage
      .split('\n')
      .filter((line) => !/^\s*at\s/.test(line))
      .join('\n');

    const withoutSecrets = withoutStackLines
      .replace(/eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/g, '[REDACTED]')
      .replace(/Bearer\s+\S+/gi, 'Bearer [REDACTED]')
      .replace(/(password|secret|token|api[_-]?key)\s*[:=]\s*\S+/gi, '$1=[REDACTED]');

    const trimmed = withoutSecrets.trim();
    if (trimmed.length === 0) {
      return null;
    }

    return trimmed.length > MAX_FAILURE_MESSAGE_LENGTH
      ? trimmed.slice(0, MAX_FAILURE_MESSAGE_LENGTH)
      : trimmed;
  }

  private static validateStalePageInput(
    input: FindStaleCheckoutAttemptsInput,
    limit: number,
  ): CheckoutAttemptInputValidationFailure | null {
    if (!Number.isInteger(limit) || limit < 1) {
      return { ok: false, code: 'INVALID_INPUT', field: 'limit', reason: 'limit must be a positive integer' };
    }
    if (limit > MAX_STALE_PAGE_SIZE) {
      return {
        ok: false,
        code: 'INVALID_INPUT',
        field: 'limit',
        reason: `limit cannot exceed ${MAX_STALE_PAGE_SIZE}`,
      };
    }
    if (!(input.heartbeatBefore instanceof Date) || Number.isNaN(input.heartbeatBefore.getTime())) {
      return {
        ok: false,
        code: 'INVALID_INPUT',
        field: 'heartbeatBefore',
        reason: 'heartbeatBefore must be a valid Date',
      };
    }
    if (input.cursor) {
      if (
        !(input.cursor.lastHeartbeatAt instanceof Date) ||
        Number.isNaN(input.cursor.lastHeartbeatAt.getTime())
      ) {
        return {
          ok: false,
          code: 'INVALID_INPUT',
          field: 'cursor.lastHeartbeatAt',
          reason: 'cursor.lastHeartbeatAt must be a valid Date',
        };
      }
      if (typeof input.cursor.id !== 'string' || input.cursor.id.length === 0) {
        return {
          ok: false,
          code: 'INVALID_INPUT',
          field: 'cursor.id',
          reason: 'cursor.id must be a non-empty string',
        };
      }
    }
    return null;
  }
}
